# Generated by Django 2.0.5 on 2018-06-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_auto_20180614_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='motivo',
            field=models.CharField(choices=[('PA', 'Primera atención'), ('CO', 'Control'), ('UA', 'Última atención')], default='PA', max_length=2),
        ),
    ]
