# Generated by Django 2.0.5 on 2018-06-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_atencion_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('CA', 'Cancelada'), ('CO', 'Completada'), ('SA', 'Sin asistencia')], default='PE', max_length=2),
        ),
    ]
