# Generated by Django 2.0.5 on 2018-06-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_atencion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='asistencia',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('CA', 'Cancelada'), ('CO', 'Completada')], default='PE', max_length=2),
        ),
    ]
