# Generated by Django 2.0.5 on 2018-07-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_auto_20180630_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='asistencia',
            field=models.BooleanField(default=False),
        ),
    ]
