# Generated by Django 2.0.6 on 2018-07-10 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_auto_20180701_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='estado',
        ),
    ]
