# Generated by Django 2.0.5 on 2018-05-31 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutricionista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(blank=True, default='', max_length=255)),
                ('nacionalidad', models.CharField(blank=True, default='', max_length=100)),
                ('observacion', models.TextField(blank=True, default='', max_length=500)),
                ('ultima_atencion', models.DateTimeField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, default=0, null=True)),
                ('talla', models.FloatField(blank=True, default=0, null=True)),
                ('imc', models.FloatField(blank=True, default=0, null=True)),
                ('diagnostico_peso', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('cintura', models.FloatField(blank=True, default=0, null=True)),
                ('presion_arterial', models.FloatField(blank=True, default=0, null=True)),
                ('h_g_t', models.FloatField(blank=True, default=0, null=True)),
                ('p_bicipital', models.FloatField(blank=True, default=0, null=True)),
                ('p_tripicital', models.FloatField(blank=True, default=0, null=True)),
                ('p_sub_escapular', models.FloatField(blank=True, default=0, null=True)),
                ('p_sub_iliaco', models.FloatField(blank=True, default=0, null=True)),
                ('c_braquial', models.FloatField(blank=True, default=0, null=True)),
                ('colesterol_mgdl', models.FloatField(blank=True, default=0, null=True)),
                ('ldl_mgdl', models.FloatField(blank=True, default=0, null=True)),
                ('tg', models.FloatField(blank=True, default=0, null=True)),
                ('hdl', models.FloatField(blank=True, default=0, null=True)),
                ('hemoglobina_gdll', models.FloatField(blank=True, default=0, null=True)),
                ('leucocitos', models.FloatField(blank=True, default=0, null=True)),
                ('plaquetas', models.FloatField(blank=True, default=0, null=True)),
                ('v_c_m', models.FloatField(blank=True, default=0, null=True)),
                ('h_c_m', models.FloatField(blank=True, default=0, null=True)),
                ('c_h_c_m', models.FloatField(blank=True, default=0, null=True)),
                ('glicemia_mgdl', models.FloatField(blank=True, default=0, null=True)),
                ('g_o_t', models.FloatField(blank=True, default=0, null=True)),
                ('g_p_t', models.FloatField(blank=True, default=0, null=True)),
                ('f_alc', models.FloatField(blank=True, default=0, null=True)),
                ('g_g_t', models.FloatField(blank=True, default=0, null=True)),
                ('bt', models.FloatField(blank=True, default=0, null=True)),
                ('bd', models.FloatField(blank=True, default=0, null=True)),
                ('e_l_p', models.FloatField(blank=True, default=0, null=True)),
                ('sodio', models.FloatField(blank=True, default=0, null=True)),
                ('potasio', models.FloatField(blank=True, default=0, null=True)),
                ('cloro', models.FloatField(blank=True, default=0, null=True)),
                ('creatinina', models.FloatField(blank=True, default=0, null=True)),
                ('v_f_g', models.FloatField(blank=True, default=0, null=True)),
                ('r_a_c', models.FloatField(blank=True, default=0, null=True)),
                ('tsh', models.FloatField(blank=True, default=0, null=True)),
                ('t3', models.FloatField(blank=True, default=0, null=True)),
                ('t4', models.FloatField(blank=True, default=0, null=True)),
                ('t_t_g_o', models.FloatField(blank=True, default=0, null=True)),
                ('glicemia_60', models.FloatField(blank=True, default=0, null=True)),
                ('glicemia_120', models.FloatField(blank=True, default=0, null=True)),
                ('perdida_peso', models.FloatField(blank=True, default=0, null=True)),
                ('ganancia_peso', models.FloatField(blank=True, default=0, null=True)),
                ('dif_deglucion', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('apetito', models.CharField(choices=[('BA', 'Baja'), ('ME', 'Media'), ('AL', 'Alta')], default='Baja', max_length=2)),
                ('vomito', models.BooleanField(default=False)),
                ('nauseas', models.BooleanField(default=False)),
                ('diuresis', models.BooleanField(default=False)),
                ('intolerancia_alimentaria', models.BooleanField(default=False)),
                ('dietas', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('nutricionista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='nutricionista.Nutricionista')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
