# Generated by Django 2.0.5 on 2018-06-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='hematocrito_gdll',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
