# Generated by Django 2.0.5 on 2018-06-11 04:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_hematocrito_gdll'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculadoraPiramidal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal_estado_nutricional', models.IntegerField(default=0)),
                ('total_kcal', models.FloatField(default=0)),
                ('vct', django.contrib.postgres.fields.jsonb.JSONField()),
                ('grupos_prociones', django.contrib.postgres.fields.jsonb.JSONField()),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
    ]
