# Generated by Django 2.0.5 on 2018-06-11 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20180611_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculadorapiramidal',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
