# Generated by Django 2.0.5 on 2018-05-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20180526_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='observacion',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
