# Generated by Django 2.0.5 on 2018-06-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_calculadorapiramidal_ultima_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculadorapiramidal',
            name='peso_a_utilizar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
