# Generated by Django 2.0.5 on 2018-05-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_auto_20180526_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='diagnostico_peso',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
