# Generated by Django 2.0.5 on 2018-06-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_auto_20180612_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico_peso',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
