# Generated by Django 2.0.6 on 2018-07-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_auto_20180614_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/'),
        ),
    ]
