# Generated by Django 2.0.6 on 2018-07-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_paciente_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='imagen',
        ),
        migrations.AddField(
            model_name='fichageneral',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/'),
        ),
    ]
