# Generated by Django 2.0.6 on 2018-07-10 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0013_auto_20180702_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichageneral',
            name='ultima_atencion',
        ),
    ]
