# Generated by Django 2.0.4 on 2018-05-03 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=254)),
                ('respuesta', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.Tema'),
        ),
    ]
