# Generated by Django 2.0.6 on 2018-07-03 22:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacion', '0002_auto_20180625_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='grupos_permitidos',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='total_kcal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
