# Generated by Django 2.0.6 on 2018-07-05 00:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacion', '0003_auto_20180703_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='grupos_permitidos_aux',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
