# Generated by Django 2.0.5 on 2018-05-20 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alimento_porcion'),
        ('paciente', '0002_auto_20180514_0256'),
        ('nutricionista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horario', models.TimeField()),
                ('alimentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='superadmin.Alimento')),
            ],
        ),
        migrations.CreateModel(
            name='PautaAlimentaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendacion', models.CharField(default='Comer sanito', max_length=2000)),
                ('comidas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricionista.Comida')),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas_alimentarias', to='nutricionista.Nutricionista')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pauta_alimentaria', to='paciente.Paciente')),
            ],
        ),
    ]
