# Generated by Django 2.0.5 on 2018-05-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alimento_porcion'),
        ('nutricionista', '0002_comida_pautaalimentaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='alimentos',
        ),
        migrations.AddField(
            model_name='comida',
            name='alimentos',
            field=models.ManyToManyField(related_name='comidas', to='superadmin.Alimento'),
        ),
        migrations.RemoveField(
            model_name='pautaalimentaria',
            name='comidas',
        ),
        migrations.AddField(
            model_name='pautaalimentaria',
            name='comidas',
            field=models.ManyToManyField(to='nutricionista.Comida'),
        ),
    ]
