# Generated by Django 2.0.5 on 2018-05-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricionista', '0003_auto_20180520_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pautaalimentaria',
            name='nombre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
