# Generated by Django 2.0.5 on 2018-05-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alimento_porcion'),
        ('nutricionista', '0004_pautaalimentaria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horario', models.TimeField()),
                ('alimentos', models.ManyToManyField(related_name='menus', to='superadmin.Alimento')),
            ],
        ),
        migrations.RemoveField(
            model_name='comida',
            name='alimentos',
        ),
        migrations.RemoveField(
            model_name='pautaalimentaria',
            name='comidas',
        ),
        migrations.DeleteModel(
            name='Comida',
        ),
        migrations.AddField(
            model_name='pautaalimentaria',
            name='menus',
            field=models.ManyToManyField(to='nutricionista.Menu'),
        ),
    ]
