# Generated by Django 2.0.5 on 2018-05-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutricionista', '0005_auto_20180520_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='horario',
        ),
        migrations.AddField(
            model_name='menu',
            name='nutricionista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nutricionista.Nutricionista'),
            preserve_default=False,
        ),
    ]
