# Generated by Django 2.0.5 on 2018-05-22 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricionista', '0006_auto_20180522_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pautaalimentaria',
            name='paciente',
        ),
    ]
