# Generated by Django 2.0.5 on 2018-05-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
