# Generated by Django 2.0.5 on 2018-05-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20180526_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='c_h_c_m',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='colesterol_mgdl',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='h_c_m',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hdl',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hemoglobina_gdll',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ldl_mgdl',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='leucocitos',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='plaquetas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='v_c_m',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
