# Generated by Django 2.0.5 on 2018-05-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_paciente_diagnostico_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='apetito',
            field=models.CharField(choices=[('BA', 'Baja'), ('ME', 'Media'), ('AL', 'Alta')], default='Baja', max_length=2),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dietas',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dif_deglucion',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='diuresis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ganancia_peso',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='intolerancia_alimentaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nauseas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='perdida_peso',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='vomito',
            field=models.BooleanField(default=False),
        ),
    ]
