# Generated by Django 2.0.5 on 2018-05-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='correo electrónico')),
                ('nombres', models.CharField(default='sin nombres especificados', max_length=255)),
                ('apellidos', models.CharField(default='sin apellidos especificados', max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('es_nutri', models.BooleanField(default=False)),
                ('es_paciente', models.BooleanField(default=False)),
                ('es_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
