# Generated by Django 2.0.5 on 2018-05-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
