# Generated by Django 2.0.4 on 2018-05-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nutri',
            new_name='es_nutri',
        ),
    ]
