# Generated by Django 2.0.5 on 2018-05-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_user_es_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellidos',
            field=models.CharField(default='sin apellidos especificados', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombres',
            field=models.CharField(default='sin nombres especificados', max_length=255),
        ),
    ]
