# Generated by Django 2.0.5 on 2018-05-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='porcion',
            field=models.IntegerField(default=1),
        ),
    ]
