# Generated by Django 2.0.5 on 2018-05-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alimento_porcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='kcal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupoalimento',
            name='kcal_prom',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
