# Generated by Django 2.0.5 on 2018-05-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_auto_20180523_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='azu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='cho',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='kcal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='lip',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='porcion',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='pro',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grupoalimento',
            name='azu_prom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grupoalimento',
            name='cho_prom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grupoalimento',
            name='kcal_prom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grupoalimento',
            name='lip_prom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grupoalimento',
            name='pro_prom',
            field=models.FloatField(),
        ),
    ]
